### Numpy scalar, vector, matrix and tensor

In [1]:
import numpy as np

In [2]:
scalar = np.array(5)
# scalar has dimension ZERO
scalar.shape

()

In [4]:
vector = np.array([1, 2, 3])
# this vector has ONE dimesion of 3
vector.shape

(3,)

In [5]:
matrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
# this matrix has TWO dimesion 3x3
matrix.shape

(3, 3)

In [6]:
# tensors are like matrices but with more dimesions
# example 3x3x2x1
tensor = np.array(
[
    [
        [[1], [2]],
        [[3], [4]],
        [[5], [6]]
    ],
    [
        [[7], [8]],
        [[9], [10]],
        [[11], [12]]
    ],
    [
        [[13], [14]],
        [[15], [16]],
        [[17], [18]]
    ],
])
tensor.shape

(3, 3, 2, 1)

In [8]:
tensor[2][1][1][0]

16

### Reshape

In [9]:
v = np.array([1, 2, 3, 4])
v.shape

(4,)

In [10]:
v

array([1, 2, 3, 4])

In [17]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [20]:
# same as RESHAPE
v[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [21]:
v[None, :]

array([[1, 2, 3, 4]])

### Element-wise operations

In [24]:
# vector plus sclar
v = np.array([1, 2, 3, 4]) + 5
v

array([6, 7, 8, 9])

In [29]:
# multipliocation vector with scalar
v = np.array([1, 2, 3, 4]) * 5
print(v)
# same as
v = np.multiply(np.array([1, 2, 3, 4]), 5)
print(v)

[ 5 10 15 20]
[ 5 10 15 20]


In [33]:
m = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(m)
# multiply Matrix by ZERO
m *= 0
print(m)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
# square matrix
m = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
m *= m
m

array([[ 121,  144,  169],
       [ 441,  484,  529],
       [ 961, 1024, 1089]])

### Dot Multiplication
```np.matmul(Mleft, Mright)```

In [66]:
# Dor multiply vector with vector
v = np.dot(np.array([0.5, 0.25]), np.array([2, 4]))
v

2.0

In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a.shape)
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(b.shape)
c = np.matmul(a, b)
print(c.shape)
c

(2, 4)
(4, 3)
(2, 3)


array([[ 70,  80,  90],
       [158, 184, 210]])

In [37]:
# if the matrices are two dimensional then np.matmul(a,b) == np.dot(a, b)
np.dot(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

### Matrix transpode
You can safely transpose in matrix multiploication if the data stored in both your original matrices is arranged as ROWS

In [39]:
c.T

array([[ 70, 158],
       [ 80, 184],
       [ 90, 210]])

In [52]:
d = c.T
d
d.shape[0]
len(d.shape)

2

**Take in consideration that a copy it is not deep** so:

In [41]:
c[0][0] = 111
d

array([[111, 158],
       [ 80, 184],
       [ 90, 210]])

## Quiz numpy

In [42]:
import numpy

In [48]:
v = [10, 2, 3, 4]
min(v)
i = np.array([v])
i -= min(v)
i

array([[8, 0, 1, 2]])

In [49]:
def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(inputs)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max

In [54]:
prepare_inputs([[1, 2], [3, 4]])

(array([[[1, 2],
         [3, 4]]]), array([[[0, 1],
         [2, 3]]]), array([[[0, 0],
         [0, 1]]]))

In [63]:
def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if len(m1.shape) != 2 or len(m2.shape) != 2 or (m1.shape[1] != m2.shape[0] and m2.shape[1] != m1.shape[0]):
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.dot(m1, m2)
    return np.dot(m2, m1)

In [56]:
multiply_inputs(np.array([[1, 2, 3]]), np.array([[1, 2], [3, 4]]))

False

In [57]:
multiply_inputs(np.array([[1, 2, 3], [4, 5, 6]]), np.array([[1, 2], [3, 4], [5, 6]]))

array([[22, 28],
       [49, 64]])

In [58]:
multiply_inputs(np.array([[1, 2], [3, 4], [5, 6]]), np.array([[1, 2, 3], [4, 5, 6]]))

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [59]:
def find_mean(values):
    # Return the average of the values in the given Python list
    # NumPy has a lot of helpful methods like this.
    return np.mean(values)

In [60]:
find_mean([1, 2, 3, 4])

2.5

In [64]:
multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))

array([[14],
       [32]])